plugins {
    id 'java'
    id 'application'
    id 'org.flywaydb.flyway' version '13.9.0'
}

group = 'sv.edu.uca.poo.boletos'
version = '1.8.0'

repositories {
    mavenCentral()
}

def javafxVersion = '21'
def javafxModules = ['base', 'graphics', 'controls', 'fxml']

def sistema = System.getProperty('os.name').toLowerCase()
def arquitectura = System.getProperty('os.arch')
def javafxPlatform
if (sistema.contains('win')) {
    javafxPlatform = 'win'
} else if (sistema.contains('mac')) {
    javafxPlatform = arquitectura == 'aarch64' ? 'mac-aarch64' : 'mac'
} else {
    javafxPlatform = arquitectura == 'aarch64' ? 'linux-aarch64' : 'linux'
}

dependencies {
    javafxModules.each { modulo ->
        implementation "org.openjfx:javafx-${modulo}:${javafxVersion}:${javafxPlatform}"
    }

    implementation 'org.postgresql:postgresql:42.7.13'
    implementation 'at.favre.lib:bcrypt:0.10.2'
    implementation 'com.zaxxer:HikariCP:5.1.0'

    implementation 'org.slf4j:slf4j-api:2.0.20'
    implementation 'ch.qos.logback:logback-classic:1.5.6'

    implementation 'org.flywaydb:flyway-core:13.9.0'
    runtimeOnly 'org.flywaydb:flyway-database-postgresql:13.9.0'

    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

application {
    mainClass = 'MainFX'
}

tasks.withType(JavaExec).configureEach {
    doFirst {
        jvmArgs = [
                '--module-path', classpath.filter { it.name.startsWith('javafx') }.asPath,
                '--add-modules', 'javafx.controls,javafx.fxml'
        ]
    }
}

test {
    useJUnitPlatform()
}