services:
  postgres:
    image: postgres:16
    container_name: boletos-postgres
    environment:
      POSTGRES_USER: boletos
      POSTGRES_PASSWORD: boletos123
      POSTGRES_DB: boletos
    ports:
      - "5432:5432"
    volumes:
      - boletos-db-data:/var/lib/postgresql/data

volumes:
  boletos-db-data: